platform: linux
inputs:
- name: code
  path: gopath/src/github.com/niclasgeiger/concourse-test
outputs:
- name: binary
  path: compiled
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.10.3-alpine3.7"
run:
  path: sh
  args:
  - -exc
  - |
    export GOPATH=$(pwd)/gopath:$(pwd)/gopath/src/github.com/niclasgeiger/concourse-test
    CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o compiled/main github.com/niclasgeiger/concourse-test
    cp gopath/src/github.com/niclasgeiger/concourse-test/Dockerfile compiled/Dockerfile