---
resources:
- name: code
  type: git
  source:
    uri: https://github.com/niclasgeiger/concourse-test
    branch: release
- name: image
  type: docker-image
  source:
    repository: niclasgeiger/concourse-test
    username: {{docker-name}}
    password: {{docker-password}}

- name: send-email
  type: email
  source:
    host: {{email-host}}
    port: "465"
    username: {{email-from}}
    password: {{email-password}}
    from: {{email-from}}
    to: {{email-to}}

jobs:
- name: Test-it
  plan:
  - get: code
    trigger: true
  - task: unit-test
    file: code/ci/tasks/unit-test.yml
    on_failure:
      put: send-email
      params:
        subject_text: "failed unit test"
        body_text: "Build just failed."

- name: Build-it
  plan:
  - get: code
    trigger: true
    passed:
    - Test-it
  - task: build-binary
    file: code/ci/tasks/build-binary.yml
  - put: image
    params:
      build: binary

