---
resources:
- name: code
  type: git
  source:
    uri: https://github.com/niclasgeiger/concourse-test
    branch: release
#- name: image
#  type: docker-image
#  source:
#    repository: niclasgeiger/concourse-test
#    username: (( docker-name ))
#    password: (( docker-password ))

#- name: send-email
#  type: email
#  source:
#    from: niclasgeiger1@googlemail.com

jobs:
- name: Build-it
  plan:
  - get: code
    trigger: true
  - task: build-binary
    file: code/ci/tasks/build-binary.yml
  - task: check_it
    config:
      platform: linux
      inputs:
      - name: binary
      image_resource:
        type: docker-image
        source:
          repository: busybox
      run:
        path: sh
        args:
        - -exc
        - |
          ls -la
          ls -la binary
          ls -la bin
          ls -la bin/main

- name: Test-it
  plan:
  - get: code
    trigger: true
    passed:
    - Build-it
  - task: build
    config:
      platform: linux
      inputs:
      - name: code
        path: gopath/src/github.com/niclasgeiger/concourse-test
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: "1.10.3-alpine3.7"
      run:
        path: sh
        args:
        - -exc
        - |
          export GOPATH=$(pwd)/gopath:$(pwd)/gopath/src/github.com/niclasgeiger/concourse-test
          cd gopath/src/github.com/niclasgeiger/concourse-test
          go test ./... -v

- name: Build-image
  plan:
  - get: code
    trigger: true
    passed:
    - Test-it
#  - out: image
#    build: code

  - task: build-binary
    file: code/ci/tasks/build-binary.yml

