---
resources:
- name: code
  type: git
  source:
    uri: https://github.com/niclasgeiger/concourse-test
    branch: release
#- name: send-email
#  type: email
#  source:
#    from: niclasgeiger1@googlemail.com

jobs:
- name: Build-it
  plan:
  - get: code
    trigger: true
  - task: build
    config:
      platform: linux
      inputs:
      - name: code
        path: /gopath/src/github.com/niclasgeiger/concourse-test
      outputs:
      - name: binary
        path: /bin/main
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: "1.10.3-alpine3.7"
      run:
        path: sh
        args:
        - -exc
        - |
          ls
          export GOPATH=$(pwd)/gopath:$(pwd)/gopath/src/github.com/niclasgeiger/concourse-test
          cd gopath/src/github.com/niclasgeiger/concourse-test
          CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /bin/main .

- name: Test-it
  plan:
  - get: code
    trigger: true
    passed:
    - Build-it
  - task: build
    config:
      platform: linux
      inputs:
      - name: code
        path: /gopath/src/github.com/niclasgeiger/concourse-test
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: "1.10.3-alpine3.7"
      run:
        path: sh
        args:
        - -exc
        - |
          ls
          export GOPATH=$(pwd)/gopath:$(pwd)/gopath/src/github.com/niclasgeiger/concourse-test
          cd gopath/src/github.com/niclasgeiger/concourse-test
          go test ./... -v

- name: Build-image
  plan:
  - get: binary
    get: code
    trigger: true
    passed:
    - Test-it
  - task: build-image
    config:
      platform: linux
      inputs:
      - name: code
        path: gopath/src/github.com/niclasgeiger/concourse-test
      - name: binary
        path: bin/main
      image_resource:
        type: docker-image
        source:
          repository: golang  # TODO: use different image
          tag: "1.10.3-alpine3.7"
      run:
        path: sh
        args:
        - -exc
        - |
          ls
