---
resources:
- name: code
  type: git
  source:
    uri: https://github.com/niclasgeiger/concourse-test
    branch: release
#- name: send-email
#  type: email
#  source:
#    from: niclasgeiger1@googlemail.com

jobs:
- name: Build-it
  plan:
  - get: code
    params:
      globs:
      - fly_linux_amd64
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: "1.10.3-alpine3.7"
      run:
        path: sh
        args:
        - -exc
        - |
          CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .